# Generated by Django 2.1 on 2020-07-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20200626_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='groceries',
            field=models.TextField(default='Fruits and Vegetables'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(default='Pradesh1', max_length=100),
        ),
    ]
